force-app/main/default/objects/Balance__c/Balance__c.object-meta.xml
<CustomObject>
    <label>Balance</label>
    <nameField>
        <displayFormat>BAL-{0000}</displayFormat>
        <label>Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>16</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/Balance_AUD__c.field-meta.xml
<CustomField>
    <fullName>Balance_AUD__c</fullName>
    <label>Balance AUD</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Balances</relationshipLabel>
    <relationshipName>Balances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Balances</relationshipLabel>
    <relationshipName>Balances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/queues/BalanceCreatorQueueable.cls
public with sharing class BalanceCreatorQueueable implements Queueable {
  private Id priceBookId;

  public BalanceCreatorQueueable(Id priceBookId) {
    this.priceBookId = priceBookId;
  }

  public void execute(QueueableContext ctx) {
    List<PricebookEntry> entries = [
      SELECT id, Product2Id, UnitPrice
      FROM PricebookEntry
      WHERE Pricebook2Id = :this.priceBookId
    ];
    List<ID> productIds = new List<ID>();
    for (PricebookEntry e : entries) {
      productIds.add(e.Product2Id);
    }
    Map<String, Decimal> totalAmounts = AssetService.getTotalAmounts(
      productIds
    );

    List<Balance__c> balances = new List<Balance__c>();
    for (PricebookEntry e : entries) {
      Decimal amount = totalAmounts.get(e.Product2Id);
      if (amount == 0) {
        continue;
      }
      Balance__c b = new Balance__c();
      b.Price_Book__c = this.priceBookId;
      b.Product__c = e.Product2Id;
      b.Balance__c = amount;
      b.Balance_AUD__c = amount * e.UnitPrice;
      balances.add(b);
    }
    insert balances;
  }
}