force-app/main/default/objects/Balance__c/Balance__c.object-meta.xml
<CustomObject>
    <label>Balance</label>
    <nameField>
        <displayFormat>BAL-{0000}</displayFormat>
        <label>Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>16</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

portfolio-app/main/default/objects/Balance__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Balances</relationshipLabel>
    <relationshipName>Balances</relationshipName>
    <type>Lookup</type>
</CustomField>

portfolio-app/main/default/objects/Balance__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Balances</relationshipLabel>
    <relationshipName>Balances</relationshipName>
    <type>Lookup</type>
</CustomField>

portfolio-app/main/default/objects/Balance__x/Balance__x.object-meta.xml
<CustomObject>
    <externalDataSource>HomeServer</externalDataSource>
    <externalName>Balance</externalName>
    <label>Balance</label>
    <pluralLabel>Balances</pluralLabel>
</CustomObject>

portfolio-app/main/default/objects/Balance__x/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>PriceBook</description>
    <externalDeveloperName>pricebookid</externalDeveloperName>
    <label>PriceBook</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Balance</relationshipLabel>
    <relationshipName>Balance</relationshipName>
    <type>Lookup</type>
</CustomField>

portfolio-app/main/default/objects/Balance__x/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <externalDeveloperName>productid</externalDeveloperName>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Balance</relationshipLabel>
    <relationshipName>Balance</relationshipName>
    <type>Lookup</type>
</CustomField>

portfolio-app/main/default/classes/services/BalanceService.cls
public with sharing class BalanceService {
    public static Balance__x[] create(PricebookEntry[] entries) {
        Id[] productIds = new List<Id>{};
        for (PricebookEntry e : entries) {
            productIds.add(e.Product2Id);
        }
        Map<String, Decimal> totalAmounts = new AssetSelector()
            .sumQuantitiesByProduct(productIds, true);

        Balance__x[] balances = new List<Balance__x>{};
        for (PricebookEntry e : entries) {
            Decimal amount = totalAmounts.get(e.Product2Id);
            if (amount == 0 || amount == null) {
                continue;
            }
            balances.add(
                new Balance__x(
                    Price_Book__c = e.Pricebook2Id,
                    Product__c = e.Product2Id,
                    Balance__c = amount,
                    BalanceAUD__c = amount * e.UnitPrice
                )
            );
        }

        Database.insertAsync(balances);
        return balances;
    }
}