force-app/main/default/objects/Balance__c/Balance__c.object-meta.xml
<CustomObject>
    <label>Balance</label>
    <nameField>
        <displayFormat>BAL-{0000}</displayFormat>
        <label>Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>16</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

portfolio-app/main/default/objects/Balance__c/fields/Balance_AUD__c.field-meta.xml
<CustomField>
    <fullName>Balance_AUD__c</fullName>
    <label>Balance AUD</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

portfolio-app/main/default/objects/Balance__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Balances</relationshipLabel>
    <relationshipName>Balances</relationshipName>
    <type>Lookup</type>
</CustomField>

portfolio-app/main/default/classes/selectors/BalanceSelector.cls
public class BalanceSelector extends fflib_SObjectSelector {
    public Schema.SObjectField[] getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Balance__c.Id,
            Balance__c.Balance__c,
            Balance__c.Balance_AUD__c,
            Balance__c.CreatedDate
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Balance__c.sObjectType;
    }

    public Balance__c[] selectById(Set<Id> idSet) {
        return (Balance__c[]) selectSObjectsById(idSet);
    }

    public Balance__c[] selectByProductId(Id productId, Integer limitCount) {
        return (Balance__c[]) Database.query(
            newQueryFactory()
                .setCondition('Product__r.id = :productId')
                .toSOQL()
        );
    }
}