base-app/main/default/objects/Balance__c/Balance__c.object-meta.xml
<CustomObject>
    <label>Balance</label>
    <nameField>
        <displayFormat>BAL-{0000}</displayFormat>
        <label>Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>16</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

portfolio-app/main/default/objects/Balance__c/fields/Balance_AUD__c.field-meta.xml
<CustomField>
    <fullName>Balance_AUD__c</fullName>
    <label>Balance AUD</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

portfolio-app/main/default/objects/Balance__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Balances</relationshipLabel>
    <relationshipName>Balances</relationshipName>
    <type>Lookup</type>
</CustomField>

base-app/main/default/classes/controllers/ProductController.cls
public with sharing class ProductController {
  @AuraEnabled(cacheable=true)
  public static List<Product2> getProductList() {
    return [
      SELECT
        Id,
        Name,
        ProductCode,
        IsActive,
        Family,
        DisplayUrl,
        (
          SELECT UnitPrice
          FROM PricebookEntries
          ORDER BY createddate DESC
          LIMIT 2
        ),
        (
          SELECT Balance__c, Balance_AUD__c
          FROM Balances__r
          ORDER BY createddate DESC
          LIMIT 1
        )
      FROM Product2
      WHERE IsActive = TRUE
    ];
  }
}