force-app/main/default/objects/Asset/fields/Amount_Taxed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Taxed__c</fullName>
    <label>Amount Taxed</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Outstanding_Tax__c.field-meta.xml
<CustomField>
    <fullName>Outstanding_Tax__c</fullName>
    <formula>Quantity__c -  Amount_Taxed__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Outstanding Tax</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Purchase.recordType-meta.xml
<RecordType>
    <fullName>Purchase</fullName>
    <active>true</active>
    <label>Purchase</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Sold.recordType-meta.xml
<RecordType>
    <fullName>Sold</fullName>
    <active>true</active>
    <label>Sold</label>
</RecordType>

force-app/main/default/objects/Capital_Gains__c/Capital_Gains__c.object-meta.xml
<CustomObject>
    <label>Capital Gains</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>Capital Gains Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Gains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capital_Gains__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

portfolio-app/main/default/objects/Capital_Gains__c/fields/Purchase__c.field-meta.xml
<CustomField>
    <fullName>Purchase__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Status</field>
            <operation>equals</operation>
            <value>Purchase</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Capital Gains Transactions</relationshipLabel>
    <relationshipName>Capital_Gains_Purchase</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

portfolio-app/main/default/objects/Capital_Gains__c/fields/Sold__c.field-meta.xml
<CustomField>
    <fullName>Sold__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sold</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Status</field>
            <operation>equals</operation>
            <value>Sold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Capital Gains Transactions</relationshipLabel>
    <relationshipName>Capital_Gains_Sold</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

portfolio-app/main/default/classes/services/CapitalGainsService_Test.cls
@isTest
public class CapitalGainsService_Test {
    @TestSetup
    static void makeData() {
        TriggerHandler.bypass('CapitalGainsTriggerHandler');

        Account acc = (Account) TestDataFactory.createSObject('Account');
        Product2 product = (Product2) TestDataFactory.createSObject('Product2');

        Asset[] purchaseAssets = (Asset[]) TestDataFactory.createSObjectList(
            'Asset',
            new Map<String, Object>{
                'Status' => 'Purchase',
                'AccountId' => acc.id,
                'Product2Id' => product.id,
                'Price__c' => 1.5,
                'Quantity__c' => 200
            },
            5
        );

        Asset[] soldAssets = (Asset[]) TestDataFactory.createSObjectList(
            'Asset',
            new Map<String, Object>{
                'Status' => 'Sold',
                'AccountId' => acc.id,
                'Product2Id' => product.id,
                'Price__c' => 1.99,
                'Quantity__c' => 65
            },
            3
        );

        TestDataFactory.createSObject(
            'Capital_Gains__c',
            new Map<String, Object>{
                'Amount__c' => 55,
                'Purchase__c' => purchaseAssets[0].id,
                'Sold__c' => soldAssets[0].id
            }
        );

        // required because trigger bypassed
        update new Asset(id = purchaseAssets[0].id, Amount_Taxed__c = 55);
        update new Asset(id = soldAssets[0].id, Amount_Taxed__c = 55);
    }

    @isTest
    static void shouldAllocateToAssetList() {
        Asset[] purchaseAssets = [
            SELECT id, Amount_Taxed__c
            FROM Asset
            WHERE Status = 'Purchase' AND Amount_Taxed__c = NULL
        ];
        System.assert(!purchaseAssets.isEmpty());

        Asset[] soldAssets = [
            SELECT id, Amount_Taxed__c
            FROM Asset
            WHERE Status = 'Sold' AND Amount_Taxed__c = NULL
        ];
        System.assert(!soldAssets.isEmpty());

        Capital_Gains__c[] results = CapitalGainsService.allocateToAsset(
            new List<Capital_Gains__c>{
                (Capital_Gains__c) TestDataFactory.createSObject(
                    'Capital_Gains__c',
                    new Map<String, Object>{
                        'Amount__c' => 35,
                        'Purchase__c' => purchaseAssets[0].id,
                        'Sold__c' => soldAssets[0].id
                    },
                    false
                ),
                (Capital_Gains__c) TestDataFactory.createSObject(
                    'Capital_Gains__c',
                    new Map<String, Object>{
                        'Amount__c' => 55,
                        'Purchase__c' => purchaseAssets[1].id,
                        'Sold__c' => soldAssets[1].id
                    },
                    false
                )
            }
        );

        Map<Id, Asset> assetResultsMap = new Map<Id, Asset>(
            [
                SELECT id, Status, Amount_Taxed__c, Outstanding_Tax__c
                FROM Asset
                WHERE
                    id IN (
                        :purchaseAssets[0].id,
                        :soldAssets[0].id,
                        :purchaseAssets[1].id,
                        :soldAssets[1].id
                    )
            ]
        );
        System.assertEquals(
            35,
            assetResultsMap.get(purchaseAssets[0].id).Amount_Taxed__c
        );
        System.assertEquals(
            35,
            assetResultsMap.get(soldAssets[0].id).Amount_Taxed__c
        );
        System.assertEquals(
            55,
            assetResultsMap.get(purchaseAssets[1].id).Amount_Taxed__c
        );
        System.assertEquals(
            55,
            assetResultsMap.get(soldAssets[1].id).Amount_Taxed__c
        );
    }

    @isTest
    static void shouldAllocateToAssetSingle() {
        Asset[] purchaseAssets = [
            SELECT id, Amount_Taxed__c
            FROM Asset
            WHERE Status = 'Purchase' AND Amount_Taxed__c > 0
        ];
        System.assert(!purchaseAssets.isEmpty());

        Asset[] soldAssets = [
            SELECT id, Amount_Taxed__c
            FROM Asset
            WHERE Status = 'Sold' AND Amount_Taxed__c > 0
        ];
        System.assert(!soldAssets.isEmpty());

        Capital_Gains__c[] results = CapitalGainsService.allocateToAsset(
            new List<Capital_Gains__c>{
                (Capital_Gains__c) TestDataFactory.createSObject(
                    'Capital_Gains__c',
                    new Map<String, Object>{
                        'Amount__c' => 5,
                        'Purchase__c' => purchaseAssets[0].id,
                        'Sold__c' => soldAssets[0].id
                    },
                    false
                )
            }
        );

        Map<Id, Asset> assetResultsMap = new Map<Id, Asset>(
            [
                SELECT id, Status, Amount_Taxed__c, Outstanding_Tax__c
                FROM Asset
                WHERE id IN (:purchaseAssets[0].id, :soldAssets[0].id)
            ]
        );
        System.assertEquals(
            60,
            assetResultsMap.get(purchaseAssets[0].id).Amount_Taxed__c
        );
        System.assertEquals(
            60,
            assetResultsMap.get(soldAssets[0].id).Amount_Taxed__c
        );
    }

    @isTest
    static void shouldFailAllocateToAsset() {
        Asset[] purchaseAssets = [
            SELECT id, Amount_Taxed__c
            FROM Asset
            WHERE Status = 'Purchase' AND Amount_Taxed__c > 0
        ];
        System.assert(!purchaseAssets.isEmpty());

        Asset[] soldAssets = [
            SELECT id, Amount_Taxed__c
            FROM Asset
            WHERE Status = 'Sold' AND Amount_Taxed__c > 0
        ];
        System.assert(!soldAssets.isEmpty());

        try {
            Capital_Gains__c[] results = CapitalGainsService.allocateToAsset(
                new List<Capital_Gains__c>{
                    (Capital_Gains__c) TestDataFactory.createSObject(
                        'Capital_Gains__c',
                        new Map<String, Object>{
                            'Amount__c' => 12,
                            'Purchase__c' => purchaseAssets[0].id,
                            'Sold__c' => soldAssets[0].id
                        },
                        false
                    )
                }
            );
            System.assert(false, 'Should not reach this assert.');
        } catch (Exception e) {
            System.assert(e instanceof DmlException);
            System.assert(
                e.getMessage()
                    .contains(
                        '67.000000000 total is greater than maximum of 65.000000000'
                    )
            );
        }

        Map<Id, Asset> assetResultsMap = new Map<Id, Asset>(
            [
                SELECT id, Status, Amount_Taxed__c, Outstanding_Tax__c
                FROM Asset
                WHERE id IN (:purchaseAssets[0].id, :soldAssets[0].id)
            ]
        );
        System.assertEquals(
            55,
            assetResultsMap.get(purchaseAssets[0].id).Amount_Taxed__c
        );
        System.assertEquals(
            55,
            assetResultsMap.get(soldAssets[0].id).Amount_Taxed__c
        );
    }
}