force-app/main/default/objects/Asset/fields/Amount_Taxed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Taxed__c</fullName>
    <label>Amount Taxed</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Purchase.recordType-meta.xml
<RecordType>
    <fullName>Purchase</fullName>
    <active>true</active>
    <label>Purchase</label>
</RecordType>

force-app/main/default/objects/Asset/recordTypes/Sold.recordType-meta.xml
<RecordType>
    <fullName>Sold</fullName>
    <active>true</active>
    <label>Sold</label>
</RecordType>

force-app/main/default/objects/Capital_Gains__c/Capital_Gains__c.object-meta.xml
<CustomObject>
    <label>Capital Gains</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>Capital Gains Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Gains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capital_Gains__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Capital_Gains__c/fields/Purchase__c.field-meta.xml
<CustomField>
    <fullName>Purchase__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Status</field>
            <operation>equals</operation>
            <value>Purchase</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Capital Gains Transactions</relationshipLabel>
    <relationshipName>Capital_Gains_Purchase</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Capital_Gains__c/fields/Sold__c.field-meta.xml
<CustomField>
    <fullName>Sold__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sold</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Status</field>
            <operation>equals</operation>
            <value>Sold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Capital Gains Transactions</relationshipLabel>
    <relationshipName>Capital_Gains_Sold</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/tests/CapitalGainsTriggerHandlerTest.cls
@isTest
public class CapitalGainsTriggerHandlerTest {
  private static Map<String, ID> setup() {
    Account acc = (Account) TestDataFactory.createSObject(
      'Account',
      new Map<String, Object>{}
    );
    Product2 prod = (Product2) TestDataFactory.createSObject(
      'Product2',
      new Map<String, Object>{}
    );
    Asset a1 = (Asset) TestDataFactory.createSObject(
      'Asset',
      new Map<String, Object>{
        'Price__c' => 1,
        'Quantity__c' => 200,
        'Status' => 'Sold',
        'PurchaseDate' => Date.newInstance(1960, 2, 17),
        'Account.id' => acc.id,
        'Product2.id' => prod.id
      }
    );
    Asset a2 = (Asset) TestDataFactory.createSObject(
      'Asset',
      new Map<String, Object>{
        'Price__c' => 1.1,
        'Quantity__c' => 250,
        'Status' => 'Purchase',
        'PurchaseDate' => Date.newInstance(1960, 2, 17),
        'Account.id' => acc.id,
        'Product2.id' => prod.id
      }
    );
    return new Map<String, ID>{ 'a1' => a1.ID, 'a2' => a2.ID };
  }

  @isTest
  static void shouldUpdateTaxedAmount() {
    Map<String, ID> testData = setup();

    Capital_Gains__c cg = new Capital_Gains__c(
      Amount__c = 100,
      Purchase__c = testData.get('a2'),
      Sold__c = testData.get('a1')
    );
    List<Capital_Gains__c> cgList = new List<Capital_Gains__c>();
    cgList.add(cg);
    CapitalGainsTriggerHandler.checkAmountTaxed(cgList);

    List<Asset> result = [
      SELECT Amount_Taxed__c
      FROM Asset
      WHERE ID IN (:testData.get('a2'), :testData.get('a1'))
    ];
    System.assertEquals(100, result[0].Amount_Taxed__c);
    System.assertEquals(100, result[1].Amount_Taxed__c);
  }

  @isTest
  static void shouldUpdateTaxedAmountMultipleEntries() {
    Map<String, ID> testData = setup();

    Capital_Gains__c cg1 = new Capital_Gains__c(
      Amount__c = 100,
      Purchase__c = testData.get('a2'),
      Sold__c = testData.get('a1')
    );
    CapitalGainsTriggerHandler.checkAmountTaxed(
      new List<Capital_Gains__c>{ cg1 }
    );

    Capital_Gains__c cg2 = new Capital_Gains__c(
      Amount__c = 100,
      Purchase__c = testData.get('a2'),
      Sold__c = testData.get('a1')
    );
    CapitalGainsTriggerHandler.checkAmountTaxed(
      new List<Capital_Gains__c>{ cg2 }
    );

    List<Asset> result = [
      SELECT Amount_Taxed__c
      FROM Asset
      WHERE ID IN (:testData.get('a2'), :testData.get('a1'))
    ];
    System.assertEquals(100, result[0].Amount_Taxed__c);
    System.assertEquals(100, result[1].Amount_Taxed__c);
  }

  @isTest
  static void shouldFailUpdateTaxedAmount() {
    Map<String, ID> testData = setup();

    Capital_Gains__c cg = new Capital_Gains__c(
      Amount__c = 1000,
      Purchase__c = testData.get('a2'),
      Sold__c = testData.get('a1')
    );
    List<Capital_Gains__c> cgList = new List<Capital_Gains__c>();
    cgList.add(cg);
    CapitalGainsTriggerHandler.checkAmountTaxed(cgList);

    List<Asset> result = [
      SELECT Amount_Taxed__c
      FROM Asset
      WHERE ID IN (:testData.get('a2'), :testData.get('a1'))
    ];
    System.assertEquals(null, result[0].Amount_Taxed__c);
    System.assertEquals(null, result[1].Amount_Taxed__c);
  }

  @isTest
  static void shouldFaliUpdateTaxedAmountMultipleEntries() {
    Map<String, ID> testData = setup();

    Capital_Gains__c cg1 = new Capital_Gains__c(
      Amount__c = 100,
      Purchase__c = testData.get('a2'),
      Sold__c = testData.get('a1')
    );
    CapitalGainsTriggerHandler.checkAmountTaxed(
      new List<Capital_Gains__c>{ cg1 }
    );

    Capital_Gains__c cg2 = new Capital_Gains__c(
      Amount__c = 1000,
      Purchase__c = testData.get('a2'),
      Sold__c = testData.get('a1')
    );
    CapitalGainsTriggerHandler.checkAmountTaxed(
      new List<Capital_Gains__c>{ cg2 }
    );

    List<Asset> result = [
      SELECT Amount_Taxed__c
      FROM Asset
      WHERE ID IN (:testData.get('a2'), :testData.get('a1'))
    ];
    System.assertEquals(100, result[0].Amount_Taxed__c);
    System.assertEquals(100, result[1].Amount_Taxed__c);
  }
}