force-app/main/default/objects/Asset/fields/Amount_Taxed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Taxed__c</fullName>
    <label>Amount Taxed</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Capital_Gains__c/Capital_Gains__c.object-meta.xml
<CustomObject>
    <label>Capital Gains</label>
    <nameField>
        <displayFormat>CG-{0000}</displayFormat>
        <label>Capital Gains Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Capital Gains</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Capital_Gains__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

portfolio-app/main/default/objects/Capital_Gains__c/fields/Purchase__c.field-meta.xml
<CustomField>
    <fullName>Purchase__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Purchase</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Status</field>
            <operation>equals</operation>
            <value>Purchase</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Capital Gains Transactions</relationshipLabel>
    <relationshipName>Capital_Gains_Purchase</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

portfolio-app/main/default/objects/Capital_Gains__c/fields/Sold__c.field-meta.xml
<CustomField>
    <fullName>Sold__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Sold</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Asset.Status</field>
            <operation>equals</operation>
            <value>Sold</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Asset</referenceTo>
    <relationshipLabel>Capital Gains Transactions</relationshipLabel>
    <relationshipName>Capital_Gains_Sold</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

portfolio-app/main/default/classes/services/CapitalGainsService.cls
public with sharing class CapitalGainsService {
    public static Capital_Gains__c[] allocateToAsset(
        Capital_Gains__c[] capitalGainsList
    ) {
        Set<Id> ids = new Set<Id>();
        for (Capital_Gains__c capitalGains : capitalGainsList) {
            ids.add(capitalGains.Purchase__c);
            ids.add(capitalGains.Sold__c);
        }

        Map<Id, Asset> assetMap = new Map<Id, Asset>(
            [
                SELECT
                    Quantity__c,
                    (SELECT Amount__c FROM Capital_Gains_Sold__r),
                    (SELECT Amount__c FROM Capital_Gains_Purchase__r)
                FROM Asset
                WHERE id IN :ids
            ]
        );

        for (Capital_Gains__c capitalGains : capitalGainsList) {
            Asset purchaseAsset = assetMap.get(capitalGains.Sold__c);
            calculateAmountByAsset(
                purchaseAsset,
                purchaseAsset.Capital_Gains_Sold__r,
                capitalGains
            );

            Asset soldAsset = assetMap.get(capitalGains.Purchase__c);
            calculateAmountByAsset(
                soldAsset,
                soldAsset.Capital_Gains_Purchase__r,
                capitalGains
            );

            if (capitalGains.hasErrors()) {
                throw new DmlException(
                    String.valueOf(capitalGains.getErrors())
                );
            }
        }

        Database.update(assetMap.values());
        return capitalGainsList;
    }

    private static void calculateAmountByAsset(
        Asset a,
        Capital_Gains__c[] cgList,
        Capital_Gains__c capitalGains
    ) {
        Decimal totalPast = 0;
        for (Capital_Gains__c cp : cgList) {
            if (cp.id != capitalGains.id) {
                totalPast = totalPast + cp.Amount__c;
            }
        }
        Decimal total = totalPast + capitalGains.Amount__c;
        if (total > a.Quantity__c) {
            capitalGains.addError(
                String.format(
                    '{0} total is greater than maximum of {1}.',
                    new List<Object>{ total, a.Quantity__c }
                )
            );
        } else {
            a.Amount_Taxed__c = total;
        }
    }
}