force-app/main/default/objects/Asset/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

core-app/main/default/objects/Asset/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Price__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated AUD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/controllers/AssetController.cls
public with sharing class AssetController {
  @AuraEnabled(cacheable=true)
  public static List<Asset> getTransactionHistory(Id productId) {
    return [
      SELECT PurchaseDate, Price__c, Quantity__c, Total_Cost__c, Status
      FROM Asset
      WHERE Product2Id = :productId
      ORDER BY CreatedDate DESC
      LIMIT 3
    ];
  }

  @AuraEnabled(cacheable=true)
  public static Decimal getTotalAmount(ID productId) {
    return AssetService.getTotalAmount(productId);
  }
}