force-app/main/default/objects/Asset/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Reward.recordType-meta.xml
<RecordType>
    <fullName>Reward</fullName>
    <active>true</active>
    <label>Reward</label>
</RecordType>

force-app/main/default/objects/Balance__c/Balance__c.object-meta.xml
<CustomObject>
    <label>Balance</label>
    <nameField>
        <displayFormat>BAL-{0000}</displayFormat>
        <label>Balance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Balances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Balance__c/fields/Balance__c.field-meta.xml
<CustomField>
    <fullName>Balance__c</fullName>
    <label>Balance</label>
    <precision>16</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/Balance_AUD__c.field-meta.xml
<CustomField>
    <fullName>Balance_AUD__c</fullName>
    <label>Balance AUD</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Balances</relationshipLabel>
    <relationshipName>Balances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Balance__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Balances</relationshipLabel>
    <relationshipName>Balances</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/queues/BalanceCreatorQueueableTest.cls
@isTest
public class BalanceCreatorQueueableTest {
  @isTest
  public static void shouldCreateBalanceEntries() {
    Product2 p = new Product2();
    p.Name = 'Ethereum';
    p.ExternalId = 'ethereum';
    p.Family = 'Crypto';
    p.IsActive = true;
    insert p;
    Account a = new Account(Name = 'blah');
    insert a;

    Id pricebookId = Test.getStandardPricebookId();
    insert new PricebookEntry(
      Pricebook2Id = pricebookId,
      Product2Id = p.id,
      UnitPrice = 1.5
    );
    insert new Asset(
      Quantity__c = 10,
      Status = 'reward',
      Product2Id = p.id,
      Name = 'blah',
      AccountId = a.id
    );

    Test.startTest();
    System.enqueueJob(new BalanceCreatorQueueable(pricebookId));
    Test.stopTest();

    List<Balance__c> result = [
      SELECT Balance__c, Balance_AUD__c
      FROM Balance__c
      WHERE Price_Book__c = :pricebookId AND Product__c = :p.id
    ];
    System.assertEquals(10, result[0].Balance__c);
    System.assertEquals(15, result[0].Balance_AUD__c);
  }
}