force-app/main/default/objects/Asset/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

core-app/main/default/objects/Asset/fields/Quantity_Real_Number__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Real_Number__c</fullName>
    <formula>IF(ISPICKVAL(Status, &apos;Sold&apos;),  -Quantity__c , Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Real Number</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Asset/recordTypes/Sold.recordType-meta.xml
<RecordType>
    <fullName>Sold</fullName>
    <active>true</active>
    <label>Sold</label>
</RecordType>

core-app/main/default/classes/services/AssetService.cls
public with sharing class AssetService {
    public static Decimal getTotalAmount(ID productId) {
        Map<String, Decimal> totals = getTotalAmounts(
            new List<ID>{ productId }
        );
        return totals.get(productId);
    }

    public static Map<String, Decimal> getTotalAmounts(List<ID> productIds) {
        AggregateResult[] groupedResults = [
            SELECT SUM(Quantity__c) Amount, Status, Product2Id
            FROM Asset
            WHERE Product2Id IN :productIds AND Product2.IsActive = TRUE
            GROUP BY Status, Product2Id
        ];

        Map<String, Decimal> totalAmounts = new Map<String, Decimal>();
        for (ID id : productIds) {
            totalAmounts.put(id, 0);
        }
        for (AggregateResult aggregate : groupedResults) {
            String productId = (String) aggregate.get('Product2Id');
            Decimal tally = totalAmounts.get(productId);
            tally = aggregate.get('Status') != 'Sold'
                ? tally + (Decimal) aggregate.get('Amount')
                : tally - (Decimal) aggregate.get('Amount');
            totalAmounts.put(productId, tally);
        }
        return totalAmounts;
    }

    public static Map<String, Decimal> getTotalAmounts(
        List<ID> productIds,
        Boolean isActive
    ) {
        AggregateResult[] groupedResults = [
            SELECT Product2Id, SUM(Quantity_Real_Number__c) Amount
            FROM Asset
            WHERE Product2Id IN :productIds AND Product2.IsActive = :isActive
            GROUP BY Product2Id
            HAVING SUM(Quantity_Real_Number__c) > 0.0000
        ];
        Map<String, Decimal> totalAmounts = new Map<String, Decimal>();
        for (AggregateResult aggregate : groupedResults) {
            totalAmounts.put(
                (String) aggregate.get('Product2Id'),
                (Decimal) aggregate.get('Amount')
            );
        }
        return totalAmounts;
    }
}