force-app/main/default/objects/Log__e/fields/Quiddity__c.field-meta.xml
<CustomField>
    <fullName>Quiddity__c</fullName>
    <label>Quiddity</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

core-app/main/default/objects/Log__e/fields/Request_Id__c.field-meta.xml
<CustomField>
    <fullName>Request_Id__c</fullName>
    <label>Request Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

core-app/main/default/objects/Log__e/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/trigger-handlers/LogTriggerHandler.cls
public with sharing class LogTriggerHandler {
  public static void afterInsert(List<Log__e> logs) {
    List<LogEvent__c> events = new List<LogEvent__c>();

    for (Log__e event : logs) {
      events.add(
        new LogEvent__c(
          Log_Data__c = event.Log_Message__c,
          Quiddity__c = event.Quiddity__c,
          Request_Id__c = event.Request_Id__c,
          Severity__c = event.Severity__c
        )
      );
    }

    List<Database.SaveResult> res = Database.insert(events, false);
    for (Database.SaveResult saveRes : res) {
      if (!saveRes.isSuccess()) {
        System.debug(
          LoggingLevel.ERROR,
          'Failed to save log message: ' + saveRes
        );
      }
    }
  }
}