core-app/main/default/objects/Asset/fields/Amount_Taxed__c.field-meta.xml
<CustomField>
    <fullName>Amount_Taxed__c</fullName>
    <label>Amount Taxed</label>
    <precision>18</precision>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

core-app/main/default/objects/Asset/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price Per Unit</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>16</precision>
    <required>true</required>
    <scale>9</scale>
    <type>Number</type>
</CustomField>

core-app/main/default/objects/Asset/fields/Quantity_Real_Number__c.field-meta.xml
<CustomField>
    <fullName>Quantity_Real_Number__c</fullName>
    <formula>IF(ISPICKVAL(Status, &apos;Sold&apos;),  -Quantity__c , Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity Real Number</label>
    <precision>18</precision>
    <scale>7</scale>
    <type>Number</type>
</CustomField>

core-app/main/default/objects/Asset/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <formula>Price__c * Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Estimated AUD</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

core-app/main/default/classes/selectors/AssetSelector.cls
public class AssetSelector extends fflib_SObjectSelector {
    public Schema.SObjectField[] getSObjectFieldList() {
        return new List<Schema.SObjectField>{
            Asset.Id,
            Asset.Name,
            Asset.Product2Id,
            Asset.Status,
            Asset.PurchaseDate,
            Asset.Price__c,
            Asset.Quantity__c,
            Asset.Total_Cost__c,
            Asset.Amount_Taxed__c
        };
    }

    public Schema.SObjectType getSObjectType() {
        return Asset.sObjectType;
    }

    public Asset[] selectById(Set<Id> idSet) {
        return (Asset[]) selectSObjectsById(idSet);
    }

    public Asset[] selectByProductId(Id productId, Integer limitCount) {
        return (Asset[]) Database.query(
            newQueryFactory()
                .setLimit(limitCount)
                .setOrdering(
                    Asset.CreatedDate,
                    fflib_QueryFactory.SortOrder.DESCENDING
                )
                .setCondition('Product2Id = :productId')
                .toSOQL()
        );
    }

    public Map<String, Decimal> sumQuantitiesByProduct(
        ID[] productIds,
        Boolean isActive
    ) {
        Map<String, Decimal> totalAmounts = new Map<String, Decimal>();
        for (AggregateResult aggregate : [
            SELECT Product2Id, SUM(Quantity_Real_Number__c) Amount
            FROM Asset
            WHERE Product2Id IN :productIds AND Product2.IsActive = :isActive
            GROUP BY Product2Id
            HAVING SUM(Quantity_Real_Number__c) > 0.0000
        ]) {
            totalAmounts.put(
                (String) aggregate.get('Product2Id'),
                (Decimal) aggregate.get('Amount')
            );
        }
        return totalAmounts;
    }
}